"""Offline, hash-verified review of the saved September 22 detail batch.

Writes a new versioned review, never observations or benchmark records.
"""
import hashlib
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urldefrag
from review_saved_pages import Tree

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'residential_land_pilots/propertywala/20260922_priority'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def extract(raw):
    tree = Tree(raw.decode('utf-8', errors='replace'))
    nodes = list(tree.root.walk())
    by_id = {n.attrs['id']: n for n in nodes if n.attrs.get('id')}
    project = 'projectSummary' in by_id
    prefix = 'project' if project else 'property'
    info = by_id.get(prefix + 'Info')
    dates = [{'label': n.text(), 'datetime': n.attrs.get('datetime')} for n in info.walk() if n.tag == 'time'] if info else []
    fields = {}
    summary = by_id.get(prefix + 'Summary')
    if summary:
        key = None
        for n in summary.walk():
            if n.tag == 'dt': key = n.text()
            elif n.tag == 'dd' and key: fields[key] = n.text()
    sections = {}
    for n in nodes:
        headings = [c for c in n.children if getattr(c, 'tag', None) == 'h3']
        for h in headings:
            if h.text() in ('Description', 'Location', 'Configurations'):
                sections[h.text()] = n.text()
    title = by_id.get(prefix + 'AutoGeneratedTitle')
    return {'page_kind': 'project' if project else 'listing', 'detail_title': title.text() if title else None,
            'detail_fields': fields, 'sections': sections, 'listing_or_project_dates': dates}


def main():
    out = SOURCE / ('review_' + datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ'))
    out.mkdir()
    protected = list((ROOT / 'magicbricks_mmr_data/derived').rglob('benchmark_snapshot.jsonl')) + [ROOT / 'magicbricks_mmr_data/records.jsonl', SOURCE / 'observations.jsonl']
    before = {str(p.relative_to(ROOT)): digest(p) for p in protected}
    cards = [json.loads(s) for s in (SOURCE / 'observations.jsonl').read_text(encoding='utf-8').splitlines()]
    card_map = {r['listing_id']: r for r in cards}
    batch = SOURCE / 'detail_batch_20260922'
    manifest = json.loads((batch / 'manifest.json').read_text(encoding='utf-8'))
    rows = []
    for meta in manifest['results']:
        ident = meta['listing_id']
        path = batch / ident / 'body.bin'
        assert digest(path) == meta['sha256'], ident + ': raw hash mismatch'
        assert meta['status'] == 200
        row = dict(card_map[ident])
        row.update(extract(path.read_bytes()))
        row.update(detail_raw_path=str(path.relative_to(ROOT)), detail_sha256=meta['sha256'], detail_observed_at=meta['observed_at'],
                   requested_markets=sorted({c['requested_market'] for c in cards if c['listing_id'] == ident}),
                   canonical_document_url=urldefrag(meta['source_card_url'])[0], reviewed_at=datetime.now(timezone.utc).isoformat(),
                   admitted_to_benchmark=False, cross_source_duplicate_status='unresolved', khadakpada_verified=False)
        if ident == 'P2369136':
            decision, reason = 'exclude_category_conflict', 'Office Space project / commercial office description conflicts with residential-land configuration; project updated 2018-02-27.'
        elif ident in ('P194298862', 'P194298592'):
            decision, reason = 'hold_area_and_locality_conflict', 'Summary says 1050 SqFeet; description says ' + ('3 guntha in Vasind, while label says Titwala.' if ident == 'P194298862' else '5.2 guntha in Vasind, while label says Thane West.')
        elif ident == 'P722942926':
            decision, reason = 'hold_price_basis_and_locality', 'Thane West label vs Vasind description; 5 lakh is a starting per-guntha price, not a verified total price for the summary area.'
        elif ident == 'P243109329':
            decision, reason = 'candidate_pending_locality_and_duplicates', 'Residential plot evidence; near Kalyan station, approximate location. No Khadakpada evidence. Same ID in Kalyan and Thane search.'
        elif ident == 'P194563462':
            decision, reason = 'candidate_pending_project_and_duplicates', 'Kasara plot advertisement, 2000 sqft / 68 lakh. Same project has a 2075 sqft / 68 lakh configuration; do not assume independent parcels or Thane city.'
        elif row['page_kind'] == 'project':
            decision, reason = 'hold_project_configuration', 'Project configuration, not an identified independent parcel. Rustomjee overlaps P194563462; Lodha mixes plot and built-villa wording. Preserve configurations separately.'
        else:
            decision, reason = 'hold_price_and_related_ads', 'Nine Mumbai ads share 100-crore pricing and near-identical marketing descriptions, with different localities/areas. Related-ad review group; not proven duplicates.'
        row.update(review_status=decision, review_reason=reason)
        rows.append(row)
    groups = defaultdict(list)
    for row in rows: groups[row['canonical_document_url']].append(row['listing_id'])
    summary = {'reviewed_at': datetime.now(timezone.utc).isoformat(), 'detail_ids_reviewed': len(rows),
               'unique_raw_hashes': len({r['detail_sha256'] for r in rows}), 'decisions': dict(Counter(r['review_status'] for r in rows)),
               'shared_document_groups': {k:v for k,v in groups.items() if len(v)>1},
               'remaining_detail_ids': sorted(set(card_map)-{r['listing_id'] for r in rows}), 'benchmark_additions': 0,
               'protected_hashes_before': before, 'protected_files_unchanged': all(digest(ROOT / p)==h for p,h in before.items())}
    assert summary['protected_files_unchanged']
    (out / 'detail_reviews.jsonl').write_text(''.join(json.dumps(r, ensure_ascii=False)+'\n' for r in rows), encoding='utf-8')
    (out / 'summary.json').write_text(json.dumps(summary, indent=2), encoding='utf-8')
    lines = ['# PropertyWala saved detail review', '', '| ID | Detail title | Decision | Reason |', '|---|---|---|---|']
    lines += [f"| {r['listing_id']} | {r['detail_title']} | {r['review_status']} | {r['review_reason']} |" for r in rows]
    (out / 'review.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print(out)
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    main()
